services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:z
    environment:
      - REDIS_RATE_LIMITING_URL=redis://redis:6379
      - LOG_THROTTLING_INFO=false
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
